# Generated by Django 5.0.2 on 2024-02-07 00:46

import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('appointment_time', models.TimeField(blank=True, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_no', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'add_appointment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Add_bed_allotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('allotment_time', models.TimeField(blank=True, null=True)),
                ('discharge_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'add_bed_allotment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Add_blood_donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, max_length=150, null=True)),
                ('donor_address', models.CharField(blank=True, max_length=500, null=True)),
                ('donor_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('donor_gender', models.CharField(blank=True, max_length=25, null=True)),
                ('donor_age', models.IntegerField(blank=True, null=True)),
                ('donor_blood_group', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'add_blood_donor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Add_department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_icon', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='depart_icon/')),
                ('depart_title', models.CharField(blank=True, max_length=150, null=True)),
                ('depart_description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'add_department',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Add_invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_title', models.CharField(blank=True, max_length=150, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=150, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=150, null=True)),
                ('patient_address', models.CharField(blank=True, max_length=500, null=True)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('pay_status', models.CharField(blank=True, max_length=15, null=True)),
                ('des_invoice', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'add_invoice',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Add_medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(blank=True, max_length=150, null=True)),
                ('medicine_category', models.CharField(blank=True, max_length=150, null=True)),
                ('medicine_category_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('medicine_price', models.IntegerField(blank=True, null=True)),
                ('total_quantity', models.IntegerField(blank=True, null=True)),
                ('manufacture_company', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'add_medicine',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Add_medicine_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_category', models.CharField(blank=True, max_length=150, null=True)),
                ('medicine_category_description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'add_medicine_category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Add_patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_no', models.CharField(blank=True, max_length=15, null=True)),
                ('patient_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('patient_blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('patient_dob', models.DateField(blank=True, null=True)),
                ('patient_gender', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'add_patient',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Add_patient_diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_date', models.DateField(blank=True, null=True)),
                ('diagnosis_time', models.TimeField(blank=True, null=True)),
                ('report_type', models.CharField(blank=True, max_length=100, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='patient_diagnosis_file/')),
                ('document_type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'add_patient_diagnosis',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Add_patient_prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_date', models.DateField(blank=True, null=True)),
                ('prescription_time', models.TimeField(blank=True, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('case_history', models.CharField(blank=True, max_length=1000, null=True)),
                ('medication', models.CharField(blank=True, max_length=1000, null=True)),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'add_patient_prescription',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Add_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('report_file', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='operation_report/')),
            ],
            options={
                'db_table': 'add_report',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Add_sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('invoice_no', models.IntegerField(blank=True, null=True)),
                ('amount_paid', models.CharField(blank=True, max_length=20, null=True)),
                ('sales_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'add_sales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Add_sales_medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('medicine_name', models.CharField(blank=True, max_length=150, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('medicine_price', models.CharField(blank=True, max_length=20, null=True)),
                ('sales_total_price', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'add_sales_medicine',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Add_to_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=150, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('invoice_no', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'add_to_cart',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Doctor_appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('appointment_time', models.TimeField(blank=True, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'doctor_appointment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Acct_signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='acct_profile/')),
                ('acct_name', models.CharField(blank=True, max_length=150, null=True)),
                ('acct_username', models.CharField(blank=True, max_length=150, null=True)),
                ('acct_email', models.EmailField(blank=True, max_length=500, null=True)),
                ('acct_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'acct_signup',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Admin_signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='admin_profile/')),
                ('admin_name', models.CharField(blank=True, max_length=150, null=True)),
                ('admin_username', models.CharField(blank=True, max_length=150, null=True)),
                ('admin_email', models.EmailField(blank=True, max_length=500, null=True)),
                ('admin_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_signup',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Doctor_signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='doctor_profile/')),
                ('doctor_fullName', models.CharField(blank=True, max_length=150, null=True)),
                ('doctor_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('doctor_email', models.EmailField(blank=True, max_length=500, null=True)),
                ('doctor_gender', models.CharField(blank=True, max_length=500, null=True)),
                ('doctor_reg_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doctor_signup',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hospital_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='user_profile/')),
                ('fullName', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hospital_reg',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Laboratory_signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='laboratory_profile/')),
                ('laboratory_name', models.CharField(blank=True, max_length=150, null=True)),
                ('laboratory_username', models.CharField(blank=True, max_length=150, null=True)),
                ('laboratory_email', models.EmailField(blank=True, max_length=500, null=True)),
                ('laboratory_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'laboratory_signup',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Patient_signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='patient_profile/')),
                ('patient_name', models.CharField(blank=True, max_length=150, null=True)),
                ('patient_address', models.CharField(blank=True, max_length=500, null=True)),
                ('patient_no', models.CharField(blank=True, max_length=20, null=True)),
                ('patient_email', models.EmailField(blank=True, max_length=500, null=True)),
                ('patient_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('patient_gender', models.CharField(blank=True, max_length=500, null=True)),
                ('patient_dob', models.DateField(blank=True, null=True)),
                ('patient_blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_signup',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pharmacy_signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='pharmacy_profile/')),
                ('pharmacy_name', models.CharField(blank=True, max_length=150, null=True)),
                ('pharmacy_email', models.EmailField(blank=True, max_length=500, null=True)),
                ('pharmacy_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('pharmacy_username', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pharmacy_signup',
                'managed': True,
            },
        ),
    ]
