# Generated by Django 5.0.2 on 2024-02-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king_care', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_patient',
            name='patient_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
