# Generated by Django 5.0.2 on 2024-02-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king_care', '0002_add_patient_patient_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_appointment',
            name='patient_no',
        ),
        migrations.AddField(
            model_name='add_appointment',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
