# Generated by Django 5.0.2 on 2024-02-13 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('king_care', '0003_remove_add_appointment_patient_no_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add_appointment',
            new_name='Add_patient_appointment',
        ),
        migrations.AlterModelTable(
            name='add_patient_appointment',
            table='add_patient_appointment',
        ),
    ]
