# Generated by Django 5.0.2 on 2024-02-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king_care', '0004_rename_add_appointment_add_patient_appointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('appointment_time', models.TimeField(blank=True, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'add_appointment',
                'managed': True,
            },
        ),
    ]
