# Generated by Django 5.0.2 on 2024-03-08 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('king_care', '0005_add_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_patient_appointment',
        ),
    ]
