# Generated by Django 5.0.2 on 2024-03-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king_care', '0006_delete_add_patient_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_patient_prescription',
            name='prescription_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='add_patient_prescription',
            name='prescription_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
