# Generated by Django 5.0.2 on 2024-03-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king_care', '0007_alter_add_patient_prescription_prescription_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_patient_prescription',
            name='patient_blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='add_patient_prescription',
            name='patient_gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
