# Generated by Django 5.0.2 on 2024-03-09 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('king_care', '0008_add_patient_prescription_patient_blood_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_report',
            name='report_file',
        ),
    ]
