# Generated by Django 5.0.2 on 2024-03-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king_care', '0009_remove_add_report_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_appointment',
            name='patient_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
