# Generated by Django 5.0.2 on 2024-03-12 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('king_care', '0010_doctor_appointment_patient_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_appointment',
            old_name='patient_number',
            new_name='patient_no',
        ),
    ]
