# Generated by Django 5.0.2 on 2024-04-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king_care', '0011_rename_patient_number_doctor_appointment_patient_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_signup',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
