# Generated by Django 5.0.2 on 2024-04-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king_care', '0012_doctor_signup_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_signup',
            name='approved',
        ),
        migrations.AddField(
            model_name='doctor_signup',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
