# Generated by Django 5.0.2 on 2024-04-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king_care', '0014_remove_doctor_signup_is_pending_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_signup',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve')], default='Pending', max_length=20),
        ),
    ]
