# Generated by Django 5.0.2 on 2024-04-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('king_care', '0015_doctor_signup_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
