# Generated by Django 5.0.2 on 2024-04-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king_care', '0016_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='acct_signup',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='hospital_reg',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='laboratory_signup',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='pharmacy_signup',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve')], default='Pending', max_length=20),
        ),
    ]
