# Generated by Django 5.0.2 on 2024-04-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king_care', '0017_acct_signup_status_hospital_reg_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy_signup',
            name='pharmacy_gender',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
