# Generated by Django 5.0.2 on 2024-04-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king_care', '0018_pharmacy_signup_pharmacy_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory_signup',
            name='laboratory_gender',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
