# Generated by Django 5.0.2 on 2024-04-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king_care', '0019_laboratory_signup_laboratory_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='acct_signup',
            name='acct_gender',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
