# Generated by Django 5.0.2 on 2024-04-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king_care', '0020_acct_signup_acct_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital_reg',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
