# Generated by Django 5.0.2 on 2024-04-06 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('king_care', '0021_hospital_reg_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_signup',
        ),
    ]
