# Generated by Django 5.0.2 on 2024-04-06 04:36

import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king_care', '0022_delete_admin_signup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='admin_profile/')),
                ('admin_name', models.CharField(blank=True, max_length=150, null=True)),
                ('admin_username', models.CharField(blank=True, max_length=150, null=True)),
                ('admin_email', models.EmailField(blank=True, max_length=500, null=True)),
                ('admin_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_signup',
                'managed': True,
            },
        ),
    ]
