# Generated by Django 5.0.2 on 2024-04-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king_care', '0023_admin_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
    ]
