# Generated by Django 5.0.2 on 2024-04-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('king_care', '0024_websitestatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebsiteStatus',
        ),
    ]
