# Generated by Django 5.0.2 on 2025-09-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king_care', '0025_delete_websitestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_patient',
            name='patient_blood_group',
        ),
        migrations.AddField(
            model_name='add_patient',
            name='patient_medical_history',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
