# Generated by Django 5.0.2 on 2025-09-30 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('king_care', '0026_remove_add_patient_patient_blood_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_department',
        ),
        migrations.RenameField(
            model_name='add_appointment',
            old_name='appointment_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='add_appointment',
            old_name='doctor_name',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='add_appointment',
            old_name='appointment_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='add_appointment',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='add_appointment',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Doctor'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='add_appointment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='king_care.patient_signup'),
        ),
        migrations.AddField(
            model_name='add_appointment',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Checked-in', 'Checked-in'), ('With Doctor', 'With Doctor'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='add_patient',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='add_patient',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
